# Read about `build.yaml` at https://pub.dev/packages/build_config
targets:
  $default:
    builders:
      json_serializable:
        options:
          create_factory: true
      json_serializable_plus:
        options:
          special_synthetic_assets: test    # lib 、  、 test    package(todo)



builders:

  json_serializable_plus:
    import: "package:json_serializable_plus/builder.dart"
    builder_factories: ["jsonSerializablePlus"]
    build_extensions: {"/$lib/$": ['']}
    auto_apply: root_package
    build_to: source
    applies_builders: ["source_gen|combining_builder"]


